#!/bin/sh
#
# Script used to download files from iTunes share

SECTION=$1
FILE=$2

if [ -z "$SECTION" -o -z "$FILE" ] ; then
	echo "Usage: `basename $0` <section> <filename>"
	echo
	echo "e.g.  `basename $0` 1 15404.mp3"
	exit 1
fi

curl http://192.168.254.2:3689/databases/$SECTION/items/$FILE > $FILE
