#!/usr/bin/python3
# -*- mode: python -*-
"""
dmr-users - converts radioid.net CSV files for DMR radios

This script converts the RadioID user CSV dump into a format that can be
imported by the AnyTone 868UV/878UV CPS.

It requires a copy of the user.csv file from RadioID.net:

  https://www.radioid.net/database/dumps

Copyright (C) 2019  Francois Marier <francois@fmarier.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import argparse
import csv
import os
import sys


def print_header():
    print('"Radio ID","Callsign","Name","City","State","Country","Remarks",'
          '"Call Type","Call Alert"', end = "\r\n")


def read_file(filename):
    with open(filename, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        first_row = True
        for row in reader:
            if not row:
                break
            if first_row:
                print_header()
                first_row = False
                continue

            s = '"%s","%s","%s %s","%s","%s","%s","%s","",""' % tuple(row)
            print(s, end = "\r\n")


def main():
    parser = argparse.ArgumentParser(
        description='Converter for RadioID.net CSV user list')
    parser.add_argument('userfile', type=str, nargs='?',
                        default='user.csv',
                        help='the user file to convert')
    args = parser.parse_args()

    # Validate the parameters
    if not os.path.isfile(args.userfile):
        print("Error: '%s' not found" % args.userfile, file=sys.stderr)
        return 1

    read_file(args.userfile)
    return 0


exit(main())
