#!/bin/sh
if xrandr | grep --silent LVDS-1 ; then
        # ThinkPad
        if xrandr | grep --silent "HDMI-3 disconnected" ; then
                xrandr -d :1 --output LVDS-1 --auto --primary
                xrandr -d :1 --output HDMI-3 --auto
        else
                xrandr -d :1 --output LVDS-1 --auto
                xrandr -d :1 --output HDMI-3 --auto --primary
        fi
        xrandr -d :1 --output DP-3 --auto
        xrandr -d :1 --output HDMI-3 --right-of LVDS-1
elif xrandr | grep --silent eDP-1 ; then
        if xrandr | grep --silent HDMI-1 ; then
                # System76
                if xrandr | grep --silent "HDMI-1 disconnected" ; then
                        xrandr -d :1 --output HDMI-1 --auto
                        xrandr -d :1 --output eDP-1 --auto --primary
                else
                        xrandr -d :1 --output eDP-1 --auto
                        xrandr -d :1 --output HDMI-1 --auto --primary
                fi
                xrandr -d :1 --output HDMI-1 --right-of eDP-1
        else
                # Framework (Intel)
                if xrandr | grep --silent "DP-4 disconnected" ; then
                        xrandr -d :0 --output DP-4 --auto
                        xrandr -d :0 --output eDP-1 --auto --primary
                else
                        xrandr -d :0 --output eDP-1 --auto
                        xrandr -d :0 --output DP-4 --auto --primary
                fi
                xrandr -d :0 --output DP-4 --right-of eDP-1
        fi
elif xrandr | grep --silent eDP-1-1 ; then
        # System76
        if xrandr | grep --silent "DP-1 disconnected" ; then
                xrandr -d :1 --output DP-1 --auto
                xrandr -d :1 --output eDP-1-1 --auto --primary
        else
                xrandr -d :1 --output eDP-1-1 --auto
                xrandr -d :1 --output DP-1 --auto --primary
        fi
        xrandr -d :1 --output DP-1 --right-of eDP-1-1
elif xrandr | grep --silent eDP ; then
        # Framework (AMD)
        if xrandr | grep --silent "DisplayPort-1 disconnected" ; then
                xrandr -d :0 --output DisplayPort-1 --auto
                xrandr -d :0 --output eDP --auto --primary
        else
                xrandr -d :0 --output eDP --auto
                xrandr -d :0 --output DisplayPort-1 --auto --primary
        fi
        xrandr -d :0 --output DisplayPort-1 --right-of eDP
else
        echo "Unsupported configuration"
fi

if test -x ~/.fehbg ; then
        ~/.fehbg
fi

# Restart workrave so that it picks up the primary monitor
killall workrave
workrave &

# Dirty hack to fix capslock since it seems to get lost often
setxkbmap -option caps:ctrl_modifier
