#!/bin/sh
xrandr -d :0 --output eDP-1-1 --auto
xrandr -d :0 --output HDMI-0 --auto
xrandr -d :0 --output HDMI-0 --left-of eDP-1-1
~/.fehbg

# Dirty hack to fix capslock since it seems to get lost often
setxkbmap -option caps:ctrl_modifier
