#!/bin/bash
CPU_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
if [ "$CPU_GOVERNOR" != "performance" ] ; then
  echo "WARNING: your main CPU is set to the $CPU_GOVERNOR governor, this may take a while."
fi

pushd ~/devel/mozilla-central
export MOZCONFIG=`pwd`/.mozconfig-desktop
./mach build $*
popd
