#!/bin/bash
#
# Examples:
#
#  fx-build -v                                  see the full gcc command line
#  fx-build browser/components/preferences      only build a portion of the code

CPU_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
if [ "$CPU_GOVERNOR" != "performance" ] ; then
  echo "WARNING: your main CPU is set to the $CPU_GOVERNOR governor, this may take a while."
fi

pushd ~/devel/mozilla-central
export MOZCONFIG=`pwd`/.mozconfig-desktop
./mach build $*
popd
