#!/bin/bash
#
# This script requires that you put the following in your ~/.gnupg/gpg.conf:
#
#   keyserver hkps://hkps.pool.sks-keyservers.net
#   keyserver-options ca-cert-file=/etc/ssl/certs/sks-keyservers.netCA.pem
#   keyserver-options honor-keyserver-url=no
#
# and download the server's public key into /etc/ssl/certs/
#
#   wget https://sks-keyservers.net/sks-keyservers.netCA.pem

/usr/bin/parcimonie > /dev/null 2>&1
if [ -d /home/francois/.git ] ; then
    GIT_DIR=/home/francois/.git git commit --quiet -m "Automated key refresh" .gnupg/pubring.gpg > /dev/null
fi
/usr/bin/gpg2 --batch --check-trustdb 2> /dev/null
