#!/bin/bash
#
# This script requires that you put the following in your ~/.gnupg/dirmngr.conf:
#
#   use-tor
#   keyserver keyserver hkps://keys.openpgp.org
#   disable-ipv6

/usr/bin/gpg --refresh-keys --quiet > /dev/null 2>&1
if [ -d /home/francois/.git ] ; then
    GIT_DIR=/home/francois/.git git commit --quiet -m "Automated key refresh" .gnupg/pubring.kbx > /dev/null
fi
/usr/bin/gpg --batch --check-trustdb --quiet 2> /dev/null
