#!/bin/bash
ALERTS_SEEN="${HOME}/.cache/wnpp-alerts-seen"
ALERTS=$(cat "$ALERTS_SEEN")
if [ -e "$ALERTS_SEEN" ] ; then
    wnpp-alert 2> /dev/null | grep -v "$ALERTS" | tee -a "$ALERTS_SEEN"
else
    wnpp-alert | tee "$ALERTS_SEEN"
fi
