#!/bin/sh
#
# Used to extract and compress audio from audio or video files

if [ ! -r "$1" ] ; then
    echo "Usage: $0 file_to_dump"
    exit 2
fi

ffmpeg -i $1 -c:a libmp3lame -ac 2 -q:a 2 $1.mp3
detox -s utf_8 "$1.mp3"
