#!/bin/bash
#
# Used to extract and compress audio from YouTube videos

if [ "z$1" = "z" ] ; then
    echo "Usage: $0 youtube_URL"
    exit 2
fi


OUTDIR=$(mktemp -d)
pushd "$OUTDIR" || exit 1
yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --restrict-filenames --add-metadata "$1"
detox -s utf_8 ./*.mp3

# Copy artist name into album field
id3v2 -C ./*.mp3
AUTHOR=$(id3v2 -R ./*.mp3 | grep '^TPE1:' | cut -f2 -d':' | awk '{$1=$1};1')
id3v2 -A "$AUTHOR" ./*.mp3

popd || exit 1
mv -i "$OUTDIR/"*.mp3 .
rmdir "$OUTDIR"
