#!/usr/bin/perl

use IPC::Open2;

$HOME="/home/francois";
$EXTERNAL_FILTER="t-prot -acelmtS -Mmutt --spass --pgp-move-vrf --pgp-short --ftr-ad --ftr-ml --diff -L$HOME/.t-prot/mlfooters -A$HOME/.t-prot/adfooters --max-lines 1000";

sub convert_date_to_local
{
    my $original_date = shift;
    my $new_date = `date -d "$original_date" +"%a, %d %b %Y %H:%M:%S %Z"`;
    chomp($new_date);
    return "Date: $new_date";
}

open2(READER, WRITER, "$EXTERNAL_FILTER");
binmode(READER, ":encoding(utf8)");
@text = ();
foreach (<>) {
#    s/^Date: (.*)$/&convert_date_to_local($1)/e;
    s/&nbsp;/ /g;
    s/&middot;/*/g;
    s/&mdash;/--/g;
    s/&rsquo;/'/g;
    s/\r//g;
    print WRITER;
}
close WRITER;
@text = <READER>;
close READER;
binmode(STDOUT, ":utf8");
print join('', @text);
