#!/bin/sh

find . -iname '*.png' -exec optipng -o7 -q {} \;
find . -iname '*.gif' -exec gifsicle -O2 -b {} \;
find . -iname '*.jpg' -exec jpegoptim -p --strip-all {} \;
find . -iname '*.jpeg' -exec jpegoptim -p --strip-all {} \;
