#!/bin/sh
#
# Based on https://askubuntu.com/questions/858347

PINENTRY_TERMINAL=/usr/bin/pinentry-curses
PINENTRY_X11=/usr/bin/pinentry-gnome3

# Action happens below!
if [ -n "$DISPLAY" -a -z "$TERM" ]; then
    exec "$PINENTRY_X11" "$@"
else
    exec "$PINENTRY_TERMINAL" "$@"
fi
