#!/bin/bash
#
# Strips non-essential parts of PNG images using pngcrush
#

if [ "z$1" = "z" ] ; then
    echo "Usage: `basename $0` file1.png [ file2.png [ file3.png ... ] ]"
    exit 1
fi

for f in $* ; do
    pngcrush -q -rem gAMA -rem alla -rem text $f $f.crushed && mv $f.crushed $f
done
