#!/usr/bin/perl -w
#
# Helper for mutt to remember mails in Emacs' Org mode
#
# Copyright: © 2009-2010 Stefano Zacchiroli <zack@upsilon.cc>
#              2012 Francois Marier <francois@fmarier.org>
#
# Taken from:
#   http://upsilon.cc/~zack/blog/posts/2010/02/integrating_Mutt_with_Org-mode/remember-mail
#
# License: GNU General Public License (GPL), version 3 or above
#
# Example of mutt macro to invoke this hitting ESC-R (to be put in ~/.muttrc):
#  macro index \eR "|~/bin/remember-mail\n"

use strict;
use Mail::Internet;
use URI::Escape;

my $msg = Mail::Internet->new(\*STDIN);
$msg->head->get('message-id') =~ /^<(.*)>$/;
my $mid = $1;
my $subject = $msg->head->get('subject') || "";
my $from = $msg->head->get('from') || "";
chomp ($subject, $from);
my $note_body = uri_escape("  Subject: $subject\n    From: $from");

exec "emacsclient", "-t", "org-protocol:/remember:/m/mutt:$mid/mail/$note_body";
