#!/bin/bash

# TODO: make fwknop optional

if [ "z$1" = "z" ]; then
        echo "Usage: `basename $0` hostname"
        exit 1
fi

TARGET_HOST="$1"
TARGET_DISPLAY=":0.0"

# Take the screenshot
#fwknop --quiet --Last-host $TARGET_HOST
SCREENSHOT_FILE="`ssh $TARGET_HOST mktemp screenshotXXXXXXXX`.jpg"
stty -echo
ssh $TARGET_HOST rm `basename $SCREENSHOT_FILE .jpg` \&\& sudo -S DISPLAY=$TARGET_DISPLAY import -window root $SCREENSHOT_FILE || exit 2
echo
stty echo

# Copy the screenshot over
OUTPUT_FILE="`mktemp ./screenshotXXXXXXXX`.jpg"
rm `basename $OUTPUT_FILE .jpg`
#fwknop --quiet --Last-host $TARGET_HOST
scp $TARGET_HOST:$SCREENSHOT_FILE $OUTPUT_FILE

# Delete screenshot from remote server
#fwknop --quiet --Last-host $TARGET_HOST
ssh $TARGET_HOST sudo rm $SCREENSHOT_FILE
