#!/bin/sh

# Clear all clipboards
xsel -p -c
xsel -s -c
xsel -b -c

# Kill sudo session
sudo -k

# Flush akregator data to disk
dbus-send --session --dest=org.kde.akregator --type=method_call /Akregator  org.kde.akregator.part.saveSettings

sync
systemctl suspend
