#!/bin/bash
#
# spascp: wrapper around the scp command for hosts which use single packet authentication
#
# External dependencies:
# - perl
#
# NOTE: for the fwknop command to work, you must first configure it in ~/.fwknoprc

# Extract the hostname from an scp destination
hostname="`echo ${!#} | perl -pe 's/^([^@]*\@)?([^:]+):.*$/$2/'`"

fwknop -n $hostname && scp $*
