#!/bin/bash
#
# spassh: wrapper around the ssh command for hosts which use single packet authentication
#
# External dependencies:
# - perl
#
# NOTE: for the fwknop command to work, you must first configure it in ~/.fwknoprc

# Extract the hostname from an scp destination
hostname="$(echo "${!#}" | perl -pe 's/^([^@]*\@)?(.*)$/$2/')"

version="$(fwknop -V | head -1 | cut -d'v' -f2 | cut -d'.' -f1)"

export http_proxy=""
if [ "$version" = "1" ] ; then
    # shellcheck disable=SC2048,SC2086
    fwknop --quiet --Last-host "$hostname" && ssh -4 $*
else
    # shellcheck disable=SC2048,SC2086
    fwknop -n "$hostname" && ssh -4 $*
fi
