#!/bin/bash
#
# spassh: wrapper around the ssh command for hosts which use single packet authentication
#
# External dependencies:
# - perl
#
# NOTE: for the fwnkop command to work, you must have previously sent correct SPA packets
#       to that host.

# Extract the hostname from an scp destination
hostname="`echo ${!#} | perl -pe 's/^([^@]*\@)?(.*)$/$2/'`"

version=`fwknop -V | head -1 | cut -d'v' -f2 | cut -d'.' -f1`

export http_proxy=""
if [ "$version" = "1" ] ; then
  fwknop --quiet --Last-host $hostname && ssh $*
else
  fwknop --last-cmd $hostname && ssh $*
fi
