#!/bin/sh

# Needed by workrave
mkdir -p /dev/shm/workrave-francois

# Desktop environment
gnome-settings-daemon &
gnome-keyring-daemon
gnome-power-manager &
gnome-screensaver &
gkrellm &
unclutter &
nm-applet &

# Vacuuming SQLite databases
find $HOME/.mozilla/ \( -name "*.sqlite" \) -execdir sqlite3 {} "vacuum" \;

# Cleanup unnecessary files
rm -rf $HOME/.cache/chromium
rm -rf $HOME/.thumbnails
rm -rf $HOME/.local/share/Trash

# Graphical programs
emacs --daemon
ionice -n7 akregator &

# Needs to be started last apparently
gcm-apply || dispwin ~/documents/color_management/laptop_screen.icc
stalonetray &
