#!/bin/bash

# Needed by workrave
mkdir -p /dev/shm/workrave-francois

# Xorg tweaks
xautolock -time 30 -locker "i3lock -c 000000 -f" &
xset s blank -dpms
setxkbmap -option caps:ctrl_modifier

# Desktop environment
/usr/bin/systemctl --user import-environment DISPLAY
/usr/libexec/gsd-xsettings &
/usr/bin/systemctl start --user ssh-agent.service
eval "$(ssh-agent)" > /dev/null
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
gnome-screensaver &
nm-applet &
/home/francois/devel/remote/user-scripts/i3-battery-indicator &
/usr/bin/systemctl start --user dunst
~/.fehbg
/usr/bin/aa-notify -p
/usr/bin/pasystray &
/usr/bin/smart-notifier &
/usr/libexec/usbauth-notifier/usbauth-notifier &
/usr/bin/redshift-gtk &

# Vacuuming SQLite databases
find "$HOME/.mozilla/" \( -name "*.sqlite" \) -execdir sqlite3 {} "vacuum" \;

# Cleanup unnecessary files
rm -rf "$HOME/.cache/chromium"
rm -rf "$HOME/.local/share/Trash"

# Applications
syncthing -no-browser &
ionice -n7 akregator &
