#!/bin/sh

# FIXME: have this run automatically
# http://www.enricozini.org/blog/2018/debian/starting-user-software

# Needed by workrave
mkdir -p /dev/shm/workrave-francois

# Xorg tweaks
xautolock -time 30 -locker "gnome-screensaver-command --lock" &
xset dpms 1800 3600 3630
setxkbmap -option caps:ctrl_modifier

# Desktop environment
/usr/lib/gnome-settings-daemon/gsd-xsettings &
gnome-keyring-daemon
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
gnome-screensaver &
nm-applet &
i3-battery-indicator &
redshift-gtk &
usbguard-applet-qt &
dunst &
~/.fehbg
/usr/bin/aa-notify -p
/usr/bin/pasystray &

# Vacuuming SQLite databases
find "$HOME/.mozilla/" \( -name "*.sqlite" \) -execdir sqlite3 {} "vacuum" \;

# Cleanup unnecessary files
rm -f "$HOME/.config/autostart/redshift-gtk.desktop"
rm -rf "$HOME/.cache/chromium"
rm -rf "$HOME/.thumbnails"
rm -rf "$HOME/.local/share/Trash"

# Applications
syncthing-gtk --minimized &
emacs --daemon
ionice -n7 akregator &
