#!/bin/bash
#
# Quickly switch between a given keyboard layout and the US Qwerty one

OTHER_LAYOUT="ca"
CURRENT=`setxkbmap -query | grep layout | perl -pe 's/^layout: +([^ ]+)$/$1/'`

if [ "$CURRENT" = "us" ] ; then
  setxkbmap $OTHER_LAYOUT
else
  setxkbmap us
fi
