#!/bin/bash

if /usr/bin/lsusb | grep 17ef:1010 > /dev/null ; then
    pacmd set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output
else
    pacmd set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-speaker
fi
