#!/bin/bash
killall VidyoDesktop
sudo /sbin/rmmod xhci_hcd
sudo /sbin/modprobe xhci_hcd

OLD_CPU_GOVERNOR="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"
if [ "$OLD_CPU_GOVERNOR" != "performance" ] ; then
    echo "WARNING: your main CPU is set to the $OLD_CPU_GOVERNOR governor, changing to the performance one."
    sudo cpufreq performance
fi

VidyoDesktop

if [ "$OLD_CPU_GOVERNOR" != "performance" ] ; then
    echo "Changing your CPU back to the $OLD_CPU_GOVERNOR governor."
    sudo cpufreq "$OLD_CPU_GOVERNOR"
fi
